name: untitled1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.6.2"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/beaches/railay-beach.jpg
    - assets/images/beaches/ruby-beach.jpg
    - assets/images/beaches/tunnels-beach.jpg
    - assets/images/beaches/Whitehaven-beaches.jpg
    - assets/images/islands/bora-bora.jpg
    - assets/images/islands/maldives.jpg
    - assets/images/islands/palawan.jpg
    - assets/images/islands/santorini.jpg
    - assets/images/deserts/atacama-desert.jpg
    - assets/images/deserts/gobi-desert.jpg
    - assets/images/deserts/namib-desert.jpg
    - assets/images/deserts/sahara-desert.jpg
    - assets/images/cities/amsterdam.jpg
    - assets/images/cities/copenhagen.jpg
    - assets/images/cities/manchester.jpg
    - assets/images/cities/san-francisco.jpg
    - assets/images/loadimage.jpg
    - assets/images/user.jpg